#! /usr/bin/env python3
import argparse
import os
import copy
import torch
torch.set_default_dtype(torch.float64)

import run_single_test

script_dir = os.path.dirname(__file__)

examples = [
    name[:-3] for name in os.listdir(os.path.join(script_dir, 'problems'))
    if name.endswith('.py') and name != "__init__.py"
]


def get_numeric(s: str) -> int | float | str:
    try:
        return int(s)
    except ValueError:
        try:
            return float(s)
        except ValueError:
            return s


def arg_matrix(args: list[str]):
    matrix = []
    for arg in args:
        key, vals_str = arg.split('=')
        vals_list = [get_numeric(v) for v in vals_str.split(',')]
        # Take care of base case
        if len(matrix) == 0:
            matrix = [{key: val} for val in vals_list]
            continue
        # If this arg has M values and we previously had N trials, should get M*N trials at this step
        prev_matrix = matrix
        matrix = []
        for val in vals_list:
            new_trials = copy.deepcopy(prev_matrix)
            for trial in new_trials:
                trial[key] = val
                matrix.append(trial)
    return matrix


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        prog='run_test_matrix',
        usage='./run_test_matrix PROBLEM [-n num_samples] [param1=val11,val12 param2=val21,val22,val23 ...]',
        description='Run an example script for nak_torch.', # Use "--" between number of trials and any parameters.',
        exit_on_error=False
    )

    parser.add_argument(
        'problem',
        help='Which example to run. Choose `test` to check the parameter sweep.',
        choices=['test'] + examples
    )

    parser.add_argument(
        '-n', '--number',
        help='Number of trials',
        type=int,
        default=1
    )

    args, parameters = parser.parse_known_args()
    print(parameters)
    # Repeat each trial N times
    matrix = arg_matrix(parameters)
    trials: list[dict[str, int | float | str]] = []
    for _ in range(args.number):
        trials.extend(copy.deepcopy(matrix))
    N = len(trials)
    if N < 1:
        raise ValueError(f"n must be >= 1, received {N}")
    elif N == 1:
        trial = trials[0]
        trial["problem"] = args.problem
        run_single_test.run_single_test(trial)
    else:
        print(f"Performing iterations 1,...,{N}!")
        for (j, trial) in enumerate(trials):
            print(f'Iteration {j+1}, trial\n{trial}')
            trial["problem"] = args.problem
            run_single_test.run_single_test(trial)
