name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
      - run: uv sync --locked --all-extras --dev
      - run: uv run ruff check src
      - run: uv run ruff format --check src
      - run: uv run pytest --junitxml=pytest.xml --cov=nak_torch --cov-report=xml
      - name: Publish pytest report
        uses: sambyeol/publish-pytest-action@v2
        if: ${{ always() }} # Even if the tests fail, publish the report
        with:
          junit-xml: pytest.xml
          coverage-xml: coverage.xml